# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-22 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('test', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bonafied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='students/bonafied')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=100, null=True)),
                ('purpose', models.CharField(max_length=200, null=True)),
                ('Fa_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='students/Internship')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('On Campus', 'On Campus'), ('Off Campus', 'Off Campus')], max_length=100, null=True)),
                ('Fa_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='students/Retest')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(choices=[('OS', 'OS'), ('CD', 'CD'), ('DS', 'DS'), ('DSD', 'DSD')], max_length=100, null=True)),
                ('test', models.CharField(choices=[('CT1', 'CT1'), ('CT2', 'CT2'), ('CT3', 'CT3')], max_length=100, null=True)),
                ('Fa_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
