# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPDFgeneratedstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('test', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accepted_students',
            unique_together=set([('proof', 'name', 'register_number', 'type', 'subject', 'test', 'purpose')]),
        ),
        migrations.AlterUniqueTogether(
            name='finalpdfgeneratedstudents',
            unique_together=set([('proof', 'name', 'register_number', 'type', 'subject', 'test', 'purpose')]),
        ),
    ]
