# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-23 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200223_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accepted_students',
            unique_together=set([('proof', 'register_number', 'type', 'subject', 'test', 'purpose')]),
        ),
    ]
