# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='proof',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='register_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
