# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200413_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/stuents/pdfs'),
        ),
    ]
